### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by deeptimathur1904** [sarveshraj/me#9]
## Description
The alignment of an ordered list is getting distorted while moving towards smaller screen sizes.

**To Reproduce**
1. Go to 'Let's talk about resiliency' article
2. Scroll all the way down to 'References'
3. Change the window sizes to see the error.

**Expected behavior**
It should be better aligned.

**Screenshots**
![Screenshot (434)](https://user-images.githubusercontent.com/25867155/79295503-73518b80-7ef6-11ea-90bb-a66cbe9181db.png)

![Screenshot (435)](https://user-images.githubusercontent.com/25867155/79295522-7fd5e400-7ef6-11ea-8ce0-3c0fc0ddb37f.png)

## Device
**Desktop (please complete the following information):**
 - OS: Windows[e.g. iOS]
 - Browser: Google chrome
 - Version 80.0.3987.149

## Additional context
One of the hacks could be to reduce the text length of the hyperlink. For example, instead of the full link, write "how to use" etc.

**Comment by deeptimathur1904** [comment]
![image](https://user-images.githubusercontent.com/25867155/79563096-bf085e80-80c9-11ea-819f-138db5b27a8e.png)

there's an issue only with an ordered list, it works fine with inordered

**Comment by sarveshraj** [comment]
Seems like an incomplete resource loading issue. Closing this as it is no longer required.
